// Hazard Forge — HLSL codegen for the material graph (Slice AV). See codegen.h.
//
// Emits a COMPLETE HLSL fragment shader that #includes shaders/pbr_core.hlsli (the shared FrameData /
// varyings / bindings / Cook-Torrance core), evaluates the graph's nodes into temporaries in
// topological order, and calls hfShadePBR(baseColor, metallic, roughness, emissive).
//
// The per-node HLSL expression in EmitNode is the TEXTUAL twin of the CPU interpreter's math in
// shader_graph.cpp — they share the per-node formula definitions by construction (Multiply -> '*',
// Add -> '+', Lerp -> lerp(), Fresnel -> pow(1-saturate(N·V),power), TextureSample -> Sample()).
// Pure CPU; no backend symbols. Deterministic (TopoOrder is deterministic; no map iteration order).
#include "material/codegen.h"

#include <sstream>
#include <string>
#include <unordered_map>

namespace hf::material {
namespace {

// Format a float as a stable HLSL literal (always with a decimal point so it stays a float literal).
std::string Lit(float x) {
    std::ostringstream o;
    o.precision(8);
    o << x;
    std::string s = o.str();
    if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
        s.find("inf") == std::string::npos && s.find("nan") == std::string::npos)
        s += ".0";
    return s;
}

// The temp variable name for a node's output.
std::string Tmp(int id) { return "n" + std::to_string(id); }

// HLSL type keyword for a Type.
std::string Ty(Type t) { return TypeName(t); }

// Find the source node id feeding `toNode`'s named port (or -1).
int SourceOf(const Graph& g, int toNode, const char* port) {
    for (const Edge& e : g.edges)
        if (e.toNode == toNode && e.toPort == port) return e.fromNode;
    return -1;
}

}  // namespace

std::string GenerateHlsl(const Graph& g) {
    ValidationResult vr = Validate(g);
    if (!vr) return "// ERROR: invalid material graph: " + vr.error + "\n";

    std::vector<int> order = TopoOrder(g);

    // Resolved output type per node (for declaring temps + slicing into hfShadePBR args).
    std::unordered_map<int, Type> typeOf;
    for (const Node& n : g.nodes) typeOf[n.id] = OutputType(g, n);

    std::ostringstream os;
    os << "// GENERATED by tools/material_codegen from a *.mat.json material graph (Slice AV).\n";
    os << "// DO NOT EDIT — regenerate from the source JSON. Shares the PBR core in pbr_core.hlsli\n";
    os << "// with the hand-written lit_pbr.frag.hlsl (identical FrameData / varyings / bindings).\n";
    os << "// (Generated under shaders/generated/, so the PBR core include is one dir up.)\n";
    os << "#include \"../pbr_core.hlsli\"\n\n";
    os << "float4 main(PSInput i) : SV_Target {\n";

    // Emit a temporary per non-sink node, in topological order.
    for (int id : order) {
        const Node* np = g.FindNode(id);
        if (!np) continue;
        const Node& n = *np;
        if (n.kind == NodeKind::PBROutput) continue;

        Type t = typeOf[n.id];
        switch (n.kind) {
            case NodeKind::Constant: {
                int c = ComponentCount(n.outType);
                os << "    " << Ty(t) << " " << Tmp(id) << " = ";
                if (c == 1) os << Lit(n.value[0]);
                else {
                    os << Ty(t) << "(";
                    for (int k = 0; k < c; ++k) { if (k) os << ", "; os << Lit(n.value[(size_t)k]); }
                    os << ")";
                }
                os << ";\n";
                break;
            }
            case NodeKind::UV:
                os << "    float2 " << Tmp(id) << " = i.uv;\n";
                break;
            case NodeKind::TextureSample: {
                int uvSrc = SourceOf(g, id, "uv");
                std::string uvExpr = (uvSrc >= 0) ? Tmp(uvSrc) : "i.uv";
                // Base-color texture binding (set 1 binding 0/1), same as lit_pbr. No implicit sRGB
                // decode here so the node returns the raw sampled texel (matching the CPU interpreter).
                os << "    float4 " << Tmp(id) << " = gBase.Sample(gBaseSmp, " << uvExpr << ");\n";
                break;
            }
            case NodeKind::Multiply: {
                int a = SourceOf(g, id, "a"), b = SourceOf(g, id, "b");
                os << "    " << Ty(t) << " " << Tmp(id) << " = "
                   << Tmp(a) << " * " << Tmp(b) << ";\n";
                break;
            }
            case NodeKind::Add: {
                int a = SourceOf(g, id, "a"), b = SourceOf(g, id, "b");
                os << "    " << Ty(t) << " " << Tmp(id) << " = "
                   << Tmp(a) << " + " << Tmp(b) << ";\n";
                break;
            }
            case NodeKind::Lerp: {
                int a = SourceOf(g, id, "a"), b = SourceOf(g, id, "b"), tt = SourceOf(g, id, "t");
                std::string tExpr = (tt >= 0) ? Tmp(tt) : "0.0";
                os << "    " << Ty(t) << " " << Tmp(id) << " = lerp("
                   << Tmp(a) << ", " << Tmp(b) << ", " << tExpr << ");\n";
                break;
            }
            case NodeKind::Fresnel:
                os << "    float " << Tmp(id) << " = pow(1.0 - hfNoV(i), " << Lit(n.power) << ");\n";
                break;
            // --- Slice AZ nodes -----------------------------------------------------------------
            case NodeKind::Swizzle: {
                int src = SourceOf(g, id, "in");
                os << "    " << Ty(t) << " " << Tmp(id) << " = " << Tmp(src) << "."
                   << n.swizzle << ";\n";
                break;
            }
            case NodeKind::MakeFloat3:
            case NodeKind::MakeFloat4: {
                int cnt = (n.kind == NodeKind::MakeFloat3) ? 3 : 4;
                const char* ports[4] = {"x", "y", "z", "w"};
                os << "    " << Ty(t) << " " << Tmp(id) << " = " << Ty(t) << "(";
                for (int k = 0; k < cnt; ++k) {
                    if (k) os << ", ";
                    os << Tmp(SourceOf(g, id, ports[k]));
                }
                os << ");\n";
                break;
            }
            case NodeKind::Dot: {
                int a = SourceOf(g, id, "a"), b = SourceOf(g, id, "b");
                os << "    float " << Tmp(id) << " = dot(" << Tmp(a) << ", " << Tmp(b) << ");\n";
                break;
            }
            case NodeKind::Normalize: {
                int src = SourceOf(g, id, "in");
                os << "    " << Ty(t) << " " << Tmp(id) << " = normalize(" << Tmp(src) << ");\n";
                break;
            }
            case NodeKind::Power: {
                int a = SourceOf(g, id, "a"), b = SourceOf(g, id, "b");
                os << "    " << Ty(t) << " " << Tmp(id) << " = pow(" << Tmp(a) << ", " << Tmp(b) << ");\n";
                break;
            }
            case NodeKind::OneMinus: {
                int src = SourceOf(g, id, "in");
                os << "    " << Ty(t) << " " << Tmp(id) << " = 1.0 - " << Tmp(src) << ";\n";
                break;
            }
            case NodeKind::Saturate: {
                int src = SourceOf(g, id, "in");
                os << "    " << Ty(t) << " " << Tmp(id) << " = saturate(" << Tmp(src) << ");\n";
                break;
            }
            case NodeKind::NormalMap: {
                // Slice BE: sample the tangent-space normal map (defaults to the interpolated UV),
                // decode 0..1 -> -1..1 (decode(c)=c*2-1, the textual twin of EvalNormalDecode), then
                // normalize. Output is a TANGENT-SPACE float3; PBROutput.normal applies the TBN below.
                int uvSrc = SourceOf(g, id, "uv");
                std::string uvExpr = (uvSrc >= 0) ? Tmp(uvSrc) : "i.uv";
                os << "    float3 " << Tmp(id) << " = normalize(gNormalMap.Sample(gNormalSmp, "
                   << uvExpr << ").xyz * 2.0 - 1.0);\n";
                break;
            }
            case NodeKind::PBROutput:
                break;
        }
    }

    // Gather the PBROutput inputs into hfShadePBR arguments, applying the documented defaults for any
    // unconnected port and slicing each source to the expected component count.
    const Node* sink = nullptr;
    for (const Node& n : g.nodes) if (n.kind == NodeKind::PBROutput) sink = &n;

    auto arg = [&](const char* port, Type want, const char* dflt) -> std::string {
        int src = SourceOf(g, sink->id, port);
        if (src < 0) return dflt;
        Type st = typeOf[src];
        std::string e = Tmp(src);
        int wantC = ComponentCount(want), haveC = ComponentCount(st);
        if (haveC == wantC) return e;
        if (wantC == 1) return e + ".x";
        if (wantC == 3) {
            if (haveC >= 3) return e + ".xyz";
            return std::string("float3(") + e + ".x, " + e + ".x, " + e + ".x)";
        }
        return e;
    };

    os << "\n";
    os << "    float3 baseColor = " << arg("baseColor", Type::Float3, "float3(1.0, 1.0, 1.0)") << ";\n";
    os << "    float  metallic  = " << arg("metallic",  Type::Float,  "0.0") << ";\n";
    os << "    float  roughness = " << arg("roughness", Type::Float,  "1.0") << ";\n";
    os << "    float3 emissive  = " << arg("emissive",  Type::Float3, "float3(0.0, 0.0, 0.0)") << ";\n";

    // Slice BE: tangent-space normal mapping. ONLY emit the TBN transform when PBROutput.normal is
    // CONNECTED — an unconnected normal keeps the EXACT pre-BE geometric-normal call below, so graphs
    // without a normal codegen BYTE-IDENTICALLY (the existing material goldens stay unchanged).
    int normalSrc = SourceOf(g, sink->id, "normal");
    if (normalSrc < 0) {
        os << "    return hfShadePBR(i, baseColor, metallic, roughness, emissive);\n";
    } else {
        // The graph normal is tangent-space (default (0,0,1) = no perturbation). Build the SAME
        // Gram-Schmidt TBN from the interpolated wnormal + wtangent that lit.frag.hlsl uses, rotate
        // the graph normal into world space, and feed THAT into the lighting core (hfShadePBRN).
        os << "    float3 nTS = " << arg("normal", Type::Float3, "float3(0.0, 0.0, 1.0)") << ";\n";
        os << "    float3 Ng_ = normalize(i.wnormal);\n";
        os << "    float3 T_  = normalize(i.wtangent - Ng_ * dot(Ng_, i.wtangent));\n";
        os << "    float3 B_  = cross(Ng_, T_);\n";
        os << "    float3x3 TBN_ = float3x3(T_, B_, Ng_);\n";
        os << "    float3 N_  = normalize(mul(nTS, TBN_));\n";
        os << "    return hfShadePBRN(i, baseColor, metallic, roughness, emissive, N_);\n";
    }
    os << "}\n";
    return os.str();
}

}  // namespace hf::material
